apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: pls-hubclusterconfig
spec:
  description: Hub Cluster Day1 Configuration
  policies:
    - pl-ocp-gitops-install
    - pl-ocp-gitops-config